import type { MLSProperty } from '../../listings-demo/types';

/**
 * Realistic mock MLS data for demo purposes.
 * Provides a complete set of listings when the live DDF API is unavailable.
 */
export const MOCK_LISTINGS: MLSProperty[] = [
    {
        ListingKey: '20100001',
        ListingId: 'W7890123',
        StandardStatus: 'Active',
        ListPrice: 1299000,
        LeaseAmount: null,
        UnparsedAddress: '45 Harbourfront Ave, Unit 3201',
        City: 'Toronto',
        StateOrProvince: 'Ontario',
        PostalCode: 'M5J 2G8',
        Country: 'Canada',
        BedroomsTotal: 3,
        BathroomsTotalInteger: 2,
        PropertySubType: 'Condominium',
        LivingArea: 1850,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Stunning waterfront condo with panoramic lake views. Floor-to-ceiling windows, premium finishes, chef\'s kitchen with quartz countertops, spacious balcony.',
        Media: [{ MediaKey: 'm1', ResourceRecordKey: '20100001', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop', ModificationTimestamp: '2026-01-15T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'W7890123', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 43.6395,
        Longitude: -79.3832,
        ParkingTotal: 2,
        YearBuilt: 2020,
        Stories: "32",
        ListingURL: '',
        ModificationTimestamp: '2026-03-20T14:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100002',
        ListingId: 'C5678901',
        StandardStatus: 'Active',
        ListPrice: 2450000,
        LeaseAmount: null,
        UnparsedAddress: '128 Rosedale Heights Dr',
        City: 'Toronto',
        StateOrProvince: 'Ontario',
        PostalCode: 'M4T 1C8',
        Country: 'Canada',
        BedroomsTotal: 5,
        BathroomsTotalInteger: 4,
        PropertySubType: 'Single Family',
        LivingArea: 3200,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Elegant detached home in prestigious Rosedale. Renovated kitchen, hardwood throughout, private garden, steps to ravine trails.',
        Media: [{ MediaKey: 'm2', ResourceRecordKey: '20100002', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop', ModificationTimestamp: '2026-02-10T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'C5678901', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 43.6788,
        Longitude: -79.3741,
        ParkingTotal: 2,
        YearBuilt: 1935,
        Stories: "2",
        ListingURL: '',
        ModificationTimestamp: '2026-03-18T09:30:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100003',
        ListingId: 'V4567890',
        StandardStatus: 'Active',
        ListPrice: 3850000,
        LeaseAmount: null,
        UnparsedAddress: '1422 West 14th Ave',
        City: 'Vancouver',
        StateOrProvince: 'British Columbia',
        PostalCode: 'V6H 1R3',
        Country: 'Canada',
        BedroomsTotal: 4,
        BathroomsTotalInteger: 3,
        PropertySubType: 'Single Family',
        LivingArea: 2800,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Modern architectural masterpiece in South Granville. Open concept with 10ft ceilings, designer kitchen, heated floors, rooftop deck with mountain views.',
        Media: [{ MediaKey: 'm3', ResourceRecordKey: '20100003', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-01T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'V4567890', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 49.2634,
        Longitude: -123.1395,
        ParkingTotal: 2,
        YearBuilt: 2022,
        Stories: "3",
        ListingURL: '',
        ModificationTimestamp: '2026-03-22T11:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100004',
        ListingId: 'E3456789',
        StandardStatus: 'Active',
        ListPrice: 549900,
        LeaseAmount: null,
        UnparsedAddress: '9802 105 St NW',
        City: 'Edmonton',
        StateOrProvince: 'Alberta',
        PostalCode: 'T5K 0Z5',
        Country: 'Canada',
        BedroomsTotal: 3,
        BathroomsTotalInteger: 2,
        PropertySubType: 'Townhouse',
        LivingArea: 1650,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Beautiful townhome in Oliver. Updated kitchen, modern fixtures, underground parking, walking distance to River Valley trails.',
        Media: [{ MediaKey: 'm4', ResourceRecordKey: '20100004', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop', ModificationTimestamp: '2026-01-20T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'E3456789', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 53.5421,
        Longitude: -113.5060,
        ParkingTotal: 1,
        YearBuilt: 2018,
        Stories: "2",
        ListingURL: '',
        ModificationTimestamp: '2026-03-15T08:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100005',
        ListingId: 'O2345678',
        StandardStatus: 'Active',
        ListPrice: 789000,
        LeaseAmount: null,
        UnparsedAddress: '55 Byward Market Sq, Unit 1802',
        City: 'Ottawa',
        StateOrProvince: 'Ontario',
        PostalCode: 'K1N 9C3',
        Country: 'Canada',
        BedroomsTotal: 2,
        BathroomsTotalInteger: 2,
        PropertySubType: 'Condominium',
        LivingArea: 1200,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Luxury condo in the heart of ByWard Market. Open floor plan, floor-to-ceiling windows, view of Parliament Hill, concierge service.',
        Media: [{ MediaKey: 'm5', ResourceRecordKey: '20100005', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop', ModificationTimestamp: '2026-02-05T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'O2345678', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 45.4262,
        Longitude: -75.6929,
        ParkingTotal: 1,
        YearBuilt: 2019,
        Stories: "18",
        ListingURL: '',
        ModificationTimestamp: '2026-03-19T16:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100006',
        ListingId: 'CG1234567',
        StandardStatus: 'Active',
        ListPrice: 675000,
        LeaseAmount: null,
        UnparsedAddress: '317 7th Ave SW',
        City: 'Calgary',
        StateOrProvince: 'Alberta',
        PostalCode: 'T2P 0A4',
        Country: 'Canada',
        BedroomsTotal: 2,
        BathroomsTotalInteger: 2,
        PropertySubType: 'Condominium',
        LivingArea: 1100,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Sleek downtown condo with stunning views of Bow River and Rockies. Modern finishes, in-suite laundry, gym & rooftop amenities.',
        Media: [{ MediaKey: 'm6', ResourceRecordKey: '20100006', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-10T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'CG1234567', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 51.0478,
        Longitude: -114.0719,
        ParkingTotal: 1,
        YearBuilt: 2021,
        Stories: "25",
        ListingURL: '',
        ModificationTimestamp: '2026-03-21T12:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100007',
        ListingId: 'M9012345',
        StandardStatus: 'Sold',
        ListPrice: 1150000,
        LeaseAmount: null,
        UnparsedAddress: '4500 Rue Sherbrooke O',
        City: 'Montreal',
        StateOrProvince: 'Quebec',
        PostalCode: 'H3Z 1E4',
        Country: 'Canada',
        BedroomsTotal: 4,
        BathroomsTotalInteger: 3,
        PropertySubType: 'Duplex',
        LivingArea: 2400,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Charming Westmount duplex with original details and modern upgrades. Private garden, garage, near shops and parks.',
        Media: [{ MediaKey: 'm7', ResourceRecordKey: '20100007', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&h=600&fit=crop', ModificationTimestamp: '2026-02-20T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'M9012345', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 45.4833,
        Longitude: -73.6004,
        ParkingTotal: 1,
        YearBuilt: 1928,
        Stories: "2",
        ListingURL: '',
        ModificationTimestamp: '2026-03-10T09:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100008',
        ListingId: 'H8901234',
        StandardStatus: 'Active',
        ListPrice: 425000,
        LeaseAmount: null,
        UnparsedAddress: '1595 Barrington St, Unit 504',
        City: 'Halifax',
        StateOrProvince: 'Nova Scotia',
        PostalCode: 'B3J 1Z7',
        Country: 'Canada',
        BedroomsTotal: 1,
        BathroomsTotalInteger: 1,
        PropertySubType: 'Condominium',
        LivingArea: 750,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Modern waterfront living in downtown Halifax. Open concept, stainless appliances, harbour views, walkable to all amenities.',
        Media: [{ MediaKey: 'm8', ResourceRecordKey: '20100008', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-05T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'H8901234', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 44.6488,
        Longitude: -63.5752,
        ParkingTotal: 1,
        YearBuilt: 2023,
        Stories: "12",
        ListingURL: '',
        ModificationTimestamp: '2026-03-23T07:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100009',
        ListingId: 'VIC7654321',
        StandardStatus: 'Active',
        ListPrice: 1875000,
        LeaseAmount: null,
        UnparsedAddress: '310 Belleville St',
        City: 'Victoria',
        StateOrProvince: 'British Columbia',
        PostalCode: 'V8V 1X2',
        Country: 'Canada',
        BedroomsTotal: 3,
        BathroomsTotalInteger: 3,
        PropertySubType: 'Single Family',
        LivingArea: 2200,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Charming heritage home with modern renovation in James Bay. Ocean views, wrap-around porch, mature landscaping, walk to Inner Harbour.',
        Media: [{ MediaKey: 'm9', ResourceRecordKey: '20100009', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-08T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'VIC7654321', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 48.4164,
        Longitude: -123.3694,
        ParkingTotal: 2,
        YearBuilt: 1912,
        Stories: "2",
        ListingURL: '',
        ModificationTimestamp: '2026-03-17T13:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100010',
        ListingId: 'W6543210',
        StandardStatus: 'Active',
        ListPrice: 349900,
        LeaseAmount: null,
        UnparsedAddress: '486 McDougall St',
        City: 'Windsor',
        StateOrProvince: 'Ontario',
        PostalCode: 'N9A 1L6',
        Country: 'Canada',
        BedroomsTotal: 3,
        BathroomsTotalInteger: 2,
        PropertySubType: 'Single Family',
        LivingArea: 1400,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Move-in ready bungalow in established neighbourhood. Updated kitchen & bath, finished basement, fenced yard, close to schools.',
        Media: [{ MediaKey: 'm10', ResourceRecordKey: '20100010', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop', ModificationTimestamp: '2026-02-28T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'W6543210', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 42.3167,
        Longitude: -83.0378,
        ParkingTotal: 1,
        YearBuilt: 1965,
        Stories: "1",
        ListingURL: '',
        ModificationTimestamp: '2026-03-14T10:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100011',
        ListingId: 'MS5432109',
        StandardStatus: 'Active',
        ListPrice: 965000,
        LeaseAmount: null,
        UnparsedAddress: '77 City Centre Dr, Unit 2509',
        City: 'Mississauga',
        StateOrProvince: 'Ontario',
        PostalCode: 'L5B 1M5',
        Country: 'Canada',
        BedroomsTotal: 2,
        BathroomsTotalInteger: 2,
        PropertySubType: 'Condominium',
        LivingArea: 1350,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Premium high-rise living at Square One. Corner unit with dual views, upgraded kitchen, den, locker & parking. Steps to transit.',
        Media: [{ MediaKey: 'm11', ResourceRecordKey: '20100011', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-12T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'MS5432109', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 43.5930,
        Longitude: -79.6426,
        ParkingTotal: 1,
        YearBuilt: 2020,
        Stories: "35",
        ListingURL: '',
        ModificationTimestamp: '2026-03-22T15:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100012',
        ListingId: 'SU4321098',
        StandardStatus: 'Active',
        ListPrice: 1695000,
        LeaseAmount: null,
        UnparsedAddress: '14855 Thrift Ave',
        City: 'Surrey',
        StateOrProvince: 'British Columbia',
        PostalCode: 'V4B 2J5',
        Country: 'Canada',
        BedroomsTotal: 5,
        BathroomsTotalInteger: 4,
        PropertySubType: 'Single Family',
        LivingArea: 3600,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Magnificent family home in White Rock. Open plan, gourmet kitchen, media room, expansive deck, beautifully landscaped, ocean glimpses.',
        Media: [{ MediaKey: 'm12', ResourceRecordKey: '20100012', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-14T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'SU4321098', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 49.0235,
        Longitude: -122.8009,
        ParkingTotal: 3,
        YearBuilt: 2019,
        Stories: "2",
        ListingURL: '',
        ModificationTimestamp: '2026-03-20T11:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100013',
        ListingId: 'HM3210987',
        StandardStatus: 'Active',
        ListPrice: 620000,
        LeaseAmount: null,
        UnparsedAddress: '150 Main St W, Unit 1414',
        City: 'Hamilton',
        StateOrProvince: 'Ontario',
        PostalCode: 'L8P 1H8',
        Country: 'Canada',
        BedroomsTotal: 2,
        BathroomsTotalInteger: 1,
        PropertySubType: 'Condominium',
        LivingArea: 980,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Sleek urban loft-style condo in vibrant downtown core. Exposed brick, 11ft ceilings, modern kitchen, walk to GO station.',
        Media: [{ MediaKey: 'm13', ResourceRecordKey: '20100013', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-16T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'HM3210987', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 43.2562,
        Longitude: -79.8690,
        ParkingTotal: 1,
        YearBuilt: 2017,
        Stories: "20",
        ListingURL: '',
        ModificationTimestamp: '2026-03-19T14:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100014',
        ListingId: 'WP2109876',
        StandardStatus: 'Active',
        ListPrice: 379900,
        LeaseAmount: null,
        UnparsedAddress: '330 River Ave',
        City: 'Winnipeg',
        StateOrProvince: 'Manitoba',
        PostalCode: 'R3L 0C6',
        Country: 'Canada',
        BedroomsTotal: 3,
        BathroomsTotalInteger: 2,
        PropertySubType: 'Single Family',
        LivingArea: 1550,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Character home in Osborne Village. Refinished hardwood, updated windows & furnace, large yard, single garage, walk everywhere.',
        Media: [{ MediaKey: 'm14', ResourceRecordKey: '20100014', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-07T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'WP2109876', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 49.8728,
        Longitude: -97.1456,
        ParkingTotal: 1,
        YearBuilt: 1950,
        Stories: "2",
        ListingURL: '',
        ModificationTimestamp: '2026-03-16T09:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100015',
        ListingId: 'BR1098765',
        StandardStatus: 'Active',
        ListPrice: 899000,
        LeaseAmount: null,
        UnparsedAddress: '25 Corporate Dr',
        City: 'Brampton',
        StateOrProvince: 'Ontario',
        PostalCode: 'L6T 5E8',
        Country: 'Canada',
        BedroomsTotal: 4,
        BathroomsTotalInteger: 3,
        PropertySubType: 'Single Family',
        LivingArea: 2600,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Spacious 4-bedroom in sought-after neighbourhood. Open concept main floor, large island kitchen, finished basement, double garage.',
        Media: [{ MediaKey: 'm15', ResourceRecordKey: '20100015', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-11T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'BR1098765', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 43.7280,
        Longitude: -79.7619,
        ParkingTotal: 2,
        YearBuilt: 2015,
        Stories: "2",
        ListingURL: '',
        ModificationTimestamp: '2026-03-21T08:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100016',
        ListingId: 'LN0987654',
        StandardStatus: 'Active',
        ListPrice: 485000,
        LeaseAmount: null,
        UnparsedAddress: '281 Dundas St',
        City: 'London',
        StateOrProvince: 'Ontario',
        PostalCode: 'N6A 1H2',
        Country: 'Canada',
        BedroomsTotal: 3,
        BathroomsTotalInteger: 2,
        PropertySubType: 'Townhouse',
        LivingArea: 1400,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Modern townhouse in downtown London. Rooftop terrace, quartz counters, premium appliances, walking distance to Western University.',
        Media: [{ MediaKey: 'm16', ResourceRecordKey: '20100016', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-09T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'LN0987654', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 42.9833,
        Longitude: -81.2497,
        ParkingTotal: 1,
        YearBuilt: 2022,
        Stories: "3",
        ListingURL: '',
        ModificationTimestamp: '2026-03-18T11:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100017',
        ListingId: 'MK8765432',
        StandardStatus: 'Sold',
        ListPrice: 1350000,
        LeaseAmount: null,
        UnparsedAddress: '8 Bur Oak Ave',
        City: 'Markham',
        StateOrProvince: 'Ontario',
        PostalCode: 'L6C 0A2',
        Country: 'Canada',
        BedroomsTotal: 4,
        BathroomsTotalInteger: 4,
        PropertySubType: 'Single Family',
        LivingArea: 3000,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Luxury executive home in Cornell. Custom millwork, chef\'s kitchen, 9ft ceilings, finished basement with wet bar, triple garage.',
        Media: [{ MediaKey: 'm17', ResourceRecordKey: '20100017', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop', ModificationTimestamp: '2026-02-25T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'MK8765432', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 43.8720,
        Longitude: -79.2578,
        ParkingTotal: 3,
        YearBuilt: 2018,
        Stories: "2",
        ListingURL: '',
        ModificationTimestamp: '2026-03-12T10:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100018',
        ListingId: 'KT7654321',
        StandardStatus: 'Active',
        ListPrice: 575000,
        LeaseAmount: null,
        UnparsedAddress: '235 King St W, Unit 808',
        City: 'Kitchener',
        StateOrProvince: 'Ontario',
        PostalCode: 'N2G 4N5',
        Country: 'Canada',
        BedroomsTotal: 2,
        BathroomsTotalInteger: 2,
        PropertySubType: 'Condominium',
        LivingArea: 1050,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Brand new condo in KW\'s tech hub. Smart-home features, floor-to-ceiling glass, in-suite laundry, steps to LRT & restaurants.',
        Media: [{ MediaKey: 'm18', ResourceRecordKey: '20100018', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-13T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'KT7654321', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 43.4516,
        Longitude: -80.4925,
        ParkingTotal: 1,
        YearBuilt: 2024,
        Stories: "15",
        ListingURL: '',
        ModificationTimestamp: '2026-03-23T09:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100019',
        ListingId: 'NF6543210',
        StandardStatus: 'Active',
        ListPrice: 699000,
        LeaseAmount: null,
        UnparsedAddress: '6380 Fallsview Blvd',
        City: 'Niagara Falls',
        StateOrProvince: 'Ontario',
        PostalCode: 'L2G 3V4',
        Country: 'Canada',
        BedroomsTotal: 3,
        BathroomsTotalInteger: 2,
        PropertySubType: 'Single Family',
        LivingArea: 1900,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Stunning home with partial Falls views. Open concept, heated pool, landscaped yard, updated kitchen & baths, close to attractions.',
        Media: [{ MediaKey: 'm19', ResourceRecordKey: '20100019', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-04T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'NF6543210', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 43.0896,
        Longitude: -79.0849,
        ParkingTotal: 2,
        YearBuilt: 2005,
        Stories: "2",
        ListingURL: '',
        ModificationTimestamp: '2026-03-20T07:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100020',
        ListingId: 'OS5432109',
        StandardStatus: 'Active',
        ListPrice: 599000,
        LeaseAmount: null,
        UnparsedAddress: '47 Simcoe St S',
        City: 'Oshawa',
        StateOrProvince: 'Ontario',
        PostalCode: 'L1H 4G5',
        Country: 'Canada',
        BedroomsTotal: 3,
        BathroomsTotalInteger: 2,
        PropertySubType: 'Single Family',
        LivingArea: 1700,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Renovated gem in downtown Oshawa. New kitchen, hardwood throughout, private backyard, walk to GO station & university.',
        Media: [{ MediaKey: 'm20', ResourceRecordKey: '20100020', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1600585153490-76fb20a32601?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-06T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'OS5432109', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 43.8961,
        Longitude: -78.8658,
        ParkingTotal: 1,
        YearBuilt: 1985,
        Stories: "2",
        ListingURL: '',
        ModificationTimestamp: '2026-03-22T06:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    // ─── Rental / Lease listings ──────────────────────────────────
    {
        ListingKey: '20100021',
        ListingId: 'TR9988776',
        StandardStatus: 'Active',
        ListPrice: null,
        LeaseAmount: 3200,
        UnparsedAddress: '180 University Ave, Unit 4201',
        City: 'Toronto',
        StateOrProvince: 'Ontario',
        PostalCode: 'M5H 0A3',
        Country: 'Canada',
        BedroomsTotal: 2,
        BathroomsTotalInteger: 2,
        PropertySubType: 'Apartment',
        LivingArea: 1100,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Luxury rental in Financial District. Fully furnished, city views, gym, pool, concierge. Walking distance to PATH and Union Station.',
        Media: [{ MediaKey: 'm21', ResourceRecordKey: '20100021', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-20T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'TR9988776', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 43.6489,
        Longitude: -79.3849,
        ParkingTotal: 1,
        YearBuilt: 2023,
        Stories: "50",
        ListingURL: '',
        ModificationTimestamp: '2026-03-24T10:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
    {
        ListingKey: '20100022',
        ListingId: 'VC8877665',
        StandardStatus: 'Active',
        ListPrice: null,
        LeaseAmount: 4500,
        UnparsedAddress: '1088 Burrard St, PH1',
        City: 'Vancouver',
        StateOrProvince: 'British Columbia',
        PostalCode: 'V6Z 2R9',
        Country: 'Canada',
        BedroomsTotal: 3,
        BathroomsTotalInteger: 2,
        PropertySubType: 'Apartment',
        LivingArea: 1600,
        LivingAreaUnits: 'square feet',
        PublicRemarks: 'Penthouse rental in Yaletown. Wraparound terrace, mountain & water views, wine fridge, designer finishes throughout.',
        Media: [{ MediaKey: 'm22', ResourceRecordKey: '20100022', LongDescription: null, MediaURL: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&h=600&fit=crop', ModificationTimestamp: '2026-03-18T10:00:00Z', Order: 1, PreferredPhotoYN: true, ResourceRecordId: 'VC8877665', ResourceName: 'Property', MediaCategory: 'Property Photo' }],
        Latitude: 49.2764,
        Longitude: -123.1252,
        ParkingTotal: 2,
        YearBuilt: 2021,
        Stories: "30",
        ListingURL: '',
        ModificationTimestamp: '2026-03-23T14:00:00Z',
        MlsStatus: null,
        PropertyType: '',
        ParkingFeatures: [],
        OriginalEntryTimestamp: '',
        CommonInterest: null,
        StructureType: [],
        Heating: [],
        LotSizeArea: null,
        LotSizeUnits: null,
        View: [],
        AssociationFee: null,
        AssociationFeeFrequency: null,
        TaxAnnualAmount: null,
        TaxYear: null,
        ZoningDescription: null,
        SubdivisionName: null,
        PropertyAttachedYN: null,
        Rooms: [],
        ListAgentKey: null,
        ListOfficeKey: null
    },
];
